sudo: required

language: cpp

services:
  - docker

addons:
  apt:
    update: true

install:
- docker build -f Dockerfile.amd64 -t communication-test-receive .
- docker run -d --name test communication-test-receive communication-test-receive --cid=112 

script:
- docker ps | grep -q test

