version: '3'


services:
    communication-test-send:
        image: ziwei000/opendlv.io-multi:communication-test-send
        command: "communication-test-send --cid=112"
        network_mode: "host"



